version: '3.7'
services:
  meteor:
    build:
      context: ./
      dockerfile: 'Dockerfile'
    container_name: meteor-container
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
    depends_on:
      - 'mongo'
      - 'redis'
    networks:
      - main-net
networks:
  main-net:
    name: main-net