version: '3.7'
services:
  api:
    build: 
      context: ./
      dockerfile: 'dev.dockerfile'
    image: node
    container_name: andresspblog-api
    ports:
      - '5000:5000'
      - '9229:9229'
    volumes:
      - './:/home/node/app'
    depends_on:
      - 'mongo'
      - 'redis'
    networks:
      - back-net
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - back-net
  mongo-express:
    image: mongo-express
    container_name: mongo-dashboard-container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - 'mongo'
    networks:
      - back-net
  redis:
    image: redis:5
    container_name: redis-container
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - '6379'
    networks:
      - back-net
networks:
  back-net:
    name: back-net