version: '3.7'
services:
  meteor:
    build: .
    image: meteor-base
    container_name: meteor-container
    ports:
      - '3000:3000'
    # volumes:
    #   - './app:/app'
    environment:
      - MODE=QA
      - ROOT_URL=${APP_ROOT_URL:-http://localhost}
      - MONGO_URL=mongodb://admin:admin@mongo:27017
      - PORT=3000
    depends_on:
      - 'mongo'
      - 'redis'
    networks:
      - main-net
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    command:
      - --storageEngine=wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - main-net
  mongo-express:
    image: mongo-express
    container_name: mongo-dashboard-container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - 'mongo'
    networks:
      - main-net
  redis:
    image: redis:5
    container_name: redis-container
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - '6379'
    networks:
      - main-net
networks:
  main-net:
    name: main-net