## TODO
version: '3.7'
services:
  meteor:
    build: 
      context: ./
      dockerfile: 'deploy.dockerfile'
    image: meteor-base
    container_name: meteor-container
    ports:
      - '3000:3000'
    # volumes:
    #   - './app:/app'
    environment:
      - NODE_ENV=production
      - ROOT_URL=${APP_ROOT_URL:-http://localhost}
      - PORT=3000